// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmaqsaslhuixacrhausl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYXFzYXNsaHVpeGFjcmhhdXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODQ0NTAsImV4cCI6MjA1NzI2MDQ1MH0._joZBvuoT7dYIbWsbzlPFTTFTRdg8Lo159bDcbtswlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);